export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_ITEM = "DELETE_ITEM";
export const SIGN_IN_USER_REQUEST = "SIGN_IN_USER_REQUEST";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAIL = "SIGN_IN_USER_FAIL";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_REQUEST";
export const CREATE_USER_FAIL = "CREATE_USER_REQUEST";
export const SAVE_SHIPPING_DETAILS = "SAVE_SHIPPING_DETAILS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";
export const CREATE_PAY_SUCCESS = "CREATE_PAY_SUCCESS";
export const CREATE_PAY_FAIL = "CREATE_PAY_FAIL";
export const CREATE_PAY_REQUEST = "CREATE_PAY_REQUEST";
export const CREATE_PAY_RESET = "CREATE_PAY_RESET";
export const EMPTYCART = "EMPTYCART";
export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAIL = "GET_ORDER_BY_ID_FAIL"

export const GET_ORDER_HISTORY_REQUEST = "GET_ORDER_HISTORY_REQUEST"
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS"
export const GET_ORDER_HISTORY_FAIL = "GET_ORDER_HISTORY_FAIL"


export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST"
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS"
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL"


export const UPDATE_USER_BY_ID_REQUST = "UPDATE_USER_BY_ID_REQUST"
export const UPDATE_USER_BY_ID_SUCCESS = "UPDATE_USER_BY_ID_SUCCESS"
export const UPDATE_USER_BY_ID_FAIL = "UPDATE_USER_BY_ID_FAIL"
export const UPDATE_USER_BY_ID_RESET = "UPDATE_USER_BY_ID_RESET"

